name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    env:
        BUILD_DIR: build

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.12.2
      with:
        arch: win32_mingw53
        
    - name: Print Variables
      shell: bash
      run: echo "current folder is $PWD and build dir is $BUILD_DIR"
    - name: Prepare build dir
      run: mkdir $PWD\$BUILD_DIR
    - name: Generate Makefiles 
      run: qmake qt/Spark.pro -o $PWD\$BUILD_DIR
    - name: Build
      shell: bash
      working-directory: $PWD\$BUILD_DIR
      run: make
